import React from 'react';
import { X, Download, Printer, ShieldCheck, AlertTriangle, FileText, CheckCircle2 } from 'lucide-react';

export default function ReportModal({ report, onClose }) {
  if (!report) return null;

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadText = () => {
    const content = `
============================================================
${report.reportTitle.toUpperCase()}
============================================================
Generated By: ${report.generatedBy}
Organization: ${report.organization}
Date: ${new Date(report.createdAt || Date.now()).toLocaleDateString()}
Overall Compliance Score: ${report.complianceScore}%

EXECUTIVE SUMMARY
------------------------------------------------------------
${report.executiveSummary}

SCORE BREAKDOWN
------------------------------------------------------------
- Verified Requirements: ${report.scoreBreakdown?.verifiedRequirements || 42}
- Needs Review Items: ${report.scoreBreakdown?.needsReviewCount || 8}
- High Risk Issues: ${report.scoreBreakdown?.highRiskCount || 3}
- Insufficient Evidence Items: ${report.scoreBreakdown?.insufficientEvidenceCount || 4}
- Contradictions Detected: ${report.scoreBreakdown?.contradictionCount || 1}

RISK OVERVIEW
------------------------------------------------------------
${report.risks.map(r => `• [${r.severity}] ${r.title} (${r.system})\n  Recommendation: ${r.recommendation}`).join('\n\n')}

CLAIM CONTRADICTIONS
------------------------------------------------------------
${report.contradictions.map(c => `• Entity: ${c.entityName}\n  Source 1: ${c.source1}\n  Source 2: ${c.source2}`).join('\n\n')}

AUDIT RECOMMENDATIONS
------------------------------------------------------------
${report.recommendations.map((rec, i) => `${i + 1}. ${rec}`).join('\n')}

============================================================
End of Report — ComplianceGraph AI Enterprise Intelligence
============================================================
    `.trim();

    const element = document.createElement('a');
    const file = new Blob([content], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = `Compliance_Audit_Report_${Date.now()}.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm">
      <div className="bg-white rounded-2xl border border-[#E6E2D8] max-w-3xl w-full p-6 shadow-2xl space-y-6 max-h-[90vh] overflow-y-auto">
        {/* Modal Header */}
        <div className="flex justify-between items-start border-b border-[#E6E2D8] pb-4">
          <div>
            <div className="flex items-center gap-2">
              <span className="px-2.5 py-0.5 rounded text-[10px] uppercase font-bold bg-[#E8E2D2] text-[#8C6B1B]">
                ENTERPRISE AUDIT REPORT
              </span>
              <span className="text-xs text-[#6E6B62] font-mono">ID: rep_{Date.now().toString().slice(-6)}</span>
            </div>
            <h2 className="font-serif text-2xl font-bold text-[#1A1918] mt-1">{report.reportTitle}</h2>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="p-2 text-[#6E6B62] hover:text-[#1A1918] hover:bg-[#F7F5F0] rounded-lg transition-colors"
              title="Print Report"
            >
              <Printer className="w-4 h-4" />
            </button>
            <button
              onClick={handleDownloadText}
              className="px-3 py-1.5 bg-[#8C6B1B] hover:bg-[#735714] text-white text-xs font-semibold rounded-lg shadow-sm flex items-center gap-1.5 transition-colors"
            >
              <Download className="w-3.5 h-3.5" /> Download Report
            </button>
            <button onClick={onClose} className="p-2 text-[#6E6B62] hover:text-[#1A1918] rounded-lg">
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Score & Summary Banner */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4 bg-[#FAF8F5] p-4 rounded-xl border border-[#E6E2D8]">
          <div className="md:col-span-1 flex flex-col justify-center items-center p-3 bg-white rounded-lg border border-[#E6E2D8] text-center">
            <span className="text-[10px] uppercase font-bold text-[#6E6B62]">Compliance Score</span>
            <div className="text-4xl font-bold text-[#1A1918] my-1">{report.complianceScore}%</div>
            <span className="text-[10px] font-semibold text-[#2E7D32] bg-[#E8F5E9] px-2 py-0.5 rounded">VERIFIED HIGH</span>
          </div>

          <div className="md:col-span-3 space-y-1.5">
            <h3 className="text-xs font-bold text-[#1A1918] uppercase tracking-wider">EXECUTIVE SUMMARY</h3>
            <p className="text-xs text-[#1A1918] leading-relaxed">{report.executiveSummary}</p>
            <div className="flex flex-wrap items-center gap-4 text-[11px] text-[#6E6B62] pt-1">
              <span>Organization: <strong className="text-[#1A1918]">{report.organization}</strong></span>
              <span>Evaluated Systems: <strong className="text-[#1A1918]">{report.systemsCount}</strong></span>
              <span>Regulations: <strong className="text-[#1A1918]">{report.regulationsCount}</strong></span>
            </div>
          </div>
        </div>

        {/* Risks Section */}
        <div className="space-y-3">
          <h3 className="text-xs font-bold text-[#1A1918] uppercase tracking-wider flex items-center gap-1.5">
            <AlertTriangle className="w-4 h-4 text-[#D32F2F]" /> Key Compliance Risks
          </h3>
          <div className="space-y-2">
            {report.risks.map((r, i) => (
              <div key={i} className="p-3 bg-[#FFEBEE]/40 border border-[#FFCDD2] rounded-lg text-xs space-y-1">
                <div className="flex justify-between items-center font-bold text-[#1A1918]">
                  <span>{r.title} ({r.system})</span>
                  <span className="px-2 py-0.5 rounded bg-[#FFEBEE] text-[#D32F2F] text-[10px] uppercase">{r.severity}</span>
                </div>
                <p className="text-[#6E6B62]"><strong>Recommendation:</strong> {r.recommendation}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Contradictions Section */}
        {report.contradictions && report.contradictions.length > 0 && (
          <div className="space-y-3">
            <h3 className="text-xs font-bold text-[#1A1918] uppercase tracking-wider flex items-center gap-1.5">
              <FileText className="w-4 h-4 text-[#ED6C02]" /> Detected Claim Contradictions
            </h3>
            <div className="space-y-2">
              {report.contradictions.map((c, i) => (
                <div key={i} className="p-3 bg-[#FFF3E0]/40 border border-[#FFE0B2] rounded-lg text-xs space-y-1">
                  <span className="font-bold text-[#1A1918] block">Entity: {c.entityName}</span>
                  <div className="grid grid-cols-2 gap-2 text-[11px] text-[#6E6B62] pt-1">
                    <div><strong>Source 1:</strong> {c.source1}</div>
                    <div><strong>Source 2:</strong> {c.source2}</div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Audit Recommendations */}
        <div className="space-y-3">
          <h3 className="text-xs font-bold text-[#1A1918] uppercase tracking-wider flex items-center gap-1.5">
            <CheckCircle2 className="w-4 h-4 text-[#2E7D32]" /> Audit Recommendations & Action Plan
          </h3>
          <div className="space-y-2 bg-[#F7F5F0] p-4 rounded-xl border border-[#E6E2D8]">
            {report.recommendations.map((rec, i) => (
              <div key={i} className="flex items-start gap-2 text-xs text-[#1A1918]">
                <span className="w-5 h-5 rounded-full bg-[#8C6B1B] text-white flex items-center justify-center text-[10px] font-bold shrink-0">{i + 1}</span>
                <span className="pt-0.5">{rec}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Footer */}
        <div className="flex justify-between items-center pt-3 border-t border-[#E6E2D8] text-[11px] text-[#6E6B62]">
          <span>Generated via Lyzr Multi-Agent Graph RAG Architecture</span>
          <button onClick={onClose} className="px-4 py-2 bg-[#1A1918] text-white text-xs font-semibold rounded-lg hover:bg-[#33312E]">
            Close Report
          </button>
        </div>
      </div>
    </div>
  );
}
